services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=FleetOps_2026!
      - MSSQL_PID=Developer
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
